# Generated by Django 2.2 on 2020-11-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PicManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='图片.jpg', max_length=32)),
                ('time', models.DateTimeField()),
                ('path', models.CharField(max_length=30)),
                ('isShow', models.CharField(choices=[('1', 'show'), ('0', 'unshow')], max_length=1)),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
    ]
