# Generated by Django 2.2 on 2020-11-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0003_auto_20201125_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picmanage',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
    ]
